"""Machine-readable catalog for the QUARTZ idea-foundry skeleton axes."""

from __future__ import annotations

from .contracts import AxisSpec, AxisState, ExecutionPlane


AXIS_SPECS: tuple[AxisSpec, ...] = (
    AxisSpec(
        "A01_stop_council",
        "Calibrated multi-signal stop council",
        AxisState.SHADOW,
        ExecutionPlane.POSTHOC,
        "quartz.idea_foundry.decision.StopCouncilSkeleton",
        "foundry_axes::StopCouncilAxis",
        ("fixed budget", "P_flip", "H1 virtual stop", "V-MCTS-style stability"),
        ("ECE", "Brier", "selective risk", "realized budget", "top1 agreement"),
        ("fit p_wrong with position-grouped splits", "add omission-risk feature", "calibrate upper risk bound"),
        ("H1 is well calibrated but low-budget thresholds are mis-tuned",),
    ),
    AxisSpec(
        "A02_static_anchor_rpo",
        "Static-anchor regularized policy improvement",
        AxisState.SEED,
        ExecutionPlane.POSTHOC,
        "quartz.idea_foundry.decision.StaticAnchorRpoSkeleton",
        "foundry_axes::StaticAnchorRpoAxis",
        ("no-refresh legacy", "exact RPO", "Gumbel root policy", "cumulative refresh"),
        ("KL-to-oracle", "simple regret", "hidden-best recall", "policy drift"),
        ("implement safe-temperature search", "preserve tail mass in Rust cache", "paired Phase-15 readout"),
    ),
    AxisSpec(
        "A03_uncertainty_decomposition",
        "MC / epistemic / drift / bias uncertainty decomposition",
        AxisState.SEED,
        ExecutionPlane.POSTHOC,
        "quartz.idea_foundry.decision.UncertaintyDecompositionSkeleton",
        "foundry_axes::UncertaintyAxis",
        ("Welford only", "visit count", "ensemble only"),
        ("coverage", "sharpness", "oracle residual correlation", "OOD calibration"),
        ("expose evaluator heads", "block-drift telemetry", "bias calibration corpus"),
    ),
    AxisSpec(
        "A04_kg_voi_allocator",
        "KG/VOI computation allocator",
        AxisState.CONDITIONAL,
        ExecutionPlane.POSTHOC,
        "quartz.idea_foundry.decision.KgVoiAllocatorSkeleton",
        "foundry_axes::KgAllocationAxis",
        ("PUCT allocation", "uniform top2", "forked VOC oracle"),
        ("regret reduction per eval", "allocation rank correlation", "decision gain per ms"),
        ("fork SAMPLE branches", "measured cost model", "top-m approximation tests"),
        ("KG stopping did not engage at low budgets; allocation remains open",),
    ),
    AxisSpec(
        "A05_gumbel_sequential_halving",
        "Gumbel without-replacement candidate scheduler",
        AxisState.MECHANISM_VALID,
        ExecutionPlane.RUST_ONLINE,
        "quartz.idea_foundry.candidates.GumbelSequentialHalvingSkeleton",
        "foundry_axes::GumbelSequentialHalvingAxis",
        ("PUCT top prior", "current gumbel_sh primitives", "Anytime SH"),
        ("candidate recall", "low-budget top1", "hidden move discovery", "evals"),
        ("resumable bracket state", "root session integration", "exact budget accounting"),
    ),
    AxisSpec(
        "A06_residual_evidence_widening",
        "Residual-partition-mass widening",
        AxisState.SEED,
        ExecutionPlane.POSTHOC,
        "quartz.idea_foundry.candidates.ResidualEvidenceWideningSkeleton",
        "foundry_axes::ResidualEvidenceAxis",
        ("standard PW", "prior top-k", "Gumbel/SH", "priced widening"),
        ("omission regret", "residual mass calibration", "free-energy truncation", "cost"),
        ("calibrated hidden-action upper scores", "trace hidden candidate metadata", "live engine WIDEN executor"),
    ),
    AxisSpec(
        "A07_jsd_locally_balanced_root",
        "JSD-preconditioned locally balanced root sampler",
        AxisState.SEED,
        ExecutionPlane.POSTHOC,
        "quartz.idea_foundry.candidates.JlbRootSamplerSkeleton",
        "foundry_axes::JlbRootAxis",
        ("prior sampling", "Boltzmann", "Gumbel", "PTSA"),
        ("coverage", "oracle KL", "JSD compute cost", "tactical recall"),
        ("common-support sibling signatures", "policy/value cache", "root-only replay harness"),
    ),
    AxisSpec(
        "A08_dynamic_live_set_particle",
        "Dynamic live-set particle root search",
        AxisState.SEED,
        ExecutionPlane.PYTHON_ONLINE,
        "quartz.idea_foundry.candidates.DynamicLiveSetParticleSkeleton",
        "foundry_axes::DynamicLiveSetAxis",
        ("Gumbel/SH", "PMCTS-inspired particles", "uniform particles"),
        ("probability-of-best calibration", "mode survival", "decision regret", "parallel scaling"),
        ("independent particle group traces", "resurrection state", "particle executor"),
    ),
    AxisSpec(
        "A09_tactical_sentinel_proof",
        "Tactical sentinel and bounded proof action",
        AxisState.SEED,
        ExecutionPlane.RUST_ONLINE,
        "quartz.idea_foundry.candidates.TacticalSentinelSkeleton",
        "foundry_axes::TacticalProofAxis",
        ("root_forced_win", "pure MCTS", "game-specific threat solver"),
        ("forced win recall", "false positive rate", "proof latency", "blunder rate"),
        ("per-game sentinel trait", "generic/tactical result separation", "bounded proof budget"),
    ),
    AxisSpec(
        "A10_prior_refresh_specialist",
        "Conditional prior-refresh specialist",
        AxisState.DORMANT,
        ExecutionPlane.RUST_ONLINE,
        "quartz.idea_foundry.decision.PriorRefreshSpecialistSkeleton",
        "foundry_axes::PriorRefreshSpecialistAxis",
        ("no-refresh legacy", "static-anchor RPO", "historical refresh"),
        ("shift-regime Elo", "policy feedback amplification", "calibration"),
        ("regime router", "weak-evaluator corpus", "non-recursive anchor contract"),
        ("current Gomoku7 evidence does not support refresh as default",),
    ),
    AxisSpec(
        "A11_entropy_margin_regime_router",
        "Entropy-margin change-point router",
        AxisState.SHADOW,
        ExecutionPlane.POSTHOC,
        "quartz.idea_foundry.systems.EntropyMarginRegimeRouterSkeleton",
        "foundry_axes::EntropyMarginRouterAxis",
        ("H3 binary burst", "margin-only", "entropy-only", "forked VOC label"),
        ("difficulty lift", "PR-AUC", "burst precision", "extra-budget gain"),
        ("threshold-free replay", "change-point features", "online continuation action"),
        ("default H3 gate fired 0/288; continuous features remain open",),
    ),
    AxisSpec(
        "A12_service_curve_scheduler",
        "Evaluator service-curve scheduler",
        AxisState.MECHANISM_VALID,
        ExecutionPlane.PYTHON_ONLINE,
        "quartz.idea_foundry.systems.ServiceCurveSchedulerSkeleton",
        "foundry_axes::ServiceCurveAxis",
        ("fixed batch", "fixed inflight", "auto-thread throughput", "auto-thread quality"),
        ("items/s", "p95 latency", "queue wait", "GPU seconds", "energy/item"),
        ("hardware profile artifact", "quality-aware coupled run", "multi-session fairness contract"),
    ),
    AxisSpec(
        "A13_pending_flow_wu_uct",
        "Pending-flow / WU-UCT parallel observer",
        AxisState.MECHANISM_VALID,
        ExecutionPlane.RUST_ONLINE,
        "quartz.idea_foundry.systems.PendingFlowWuUctSkeleton",
        "foundry_axes::PendingFlowAxis",
        ("fixed VL", "adaptive split VL", "WU-UCT-style pending"),
        ("duplicate rate", "pessimism", "agreement", "NPS", "max pending"),
        ("pending fields in foundry snapshot", "selection-only integration", "certificate exclusion test"),
    ),
    AxisSpec(
        "A14_semantic_path_lsh",
        "High-thread semantic whole-path diversity",
        AxisState.SEED,
        ExecutionPlane.RUST_ONLINE,
        "quartz.idea_foundry.systems.SemanticPathLshSkeleton",
        "foundry_axes::SemanticPathLshAxis",
        ("adaptive VL", "edge duplicate control", "random path diversification"),
        ("semantic overlap", "batch diversity", "decision gain", "CPU overhead"),
        ("path shingles telemetry", "MinHash cache", "high-thread activation guard"),
        ("edge-duplicate superiority claim is rejected; semantic overlap is a new scope",),
    ),
    AxisSpec(
        "A15_b13_curvature_readout",
        "B13 finite-N curvature readout and target smoothing",
        AxisState.SHADOW,
        ExecutionPlane.POSTHOC,
        "quartz.idea_foundry.analysis.B13CurvatureReadoutSkeleton",
        "foundry_axes::B13ReadoutAxis",
        ("A4", "B5", "visit readout", "RPO readout"),
        ("KL-to-oracle", "top1", "topk", "training gradient", "Elo"),
        ("separate readout/selection/target roles", "training target ablation"),
        ("trained-net traces show decision-neutral KL improvement only",),
    ),
    AxisSpec(
        "A16_coherence_signed_path_shadow",
        "Coherence-gated signed path disagreement shadow",
        AxisState.ANALYSIS_ONLY,
        ExecutionPlane.ANALYSIS,
        "quartz.idea_foundry.analysis.CoherenceSignedPathShadowSkeleton",
        "foundry_axes::SignedPathAxis",
        ("ordinary disagreement", "H1", "revision features"),
        ("incremental log loss", "pre-flip detection", "feature decay", "overhead"),
        ("observable phase definition", "classical-limit gate", "incremental prediction test"),
    ),
    AxisSpec(
        "A17_physics_falsifiers",
        "Physics-analogy falsification dashboard",
        AxisState.ANALYSIS_ONLY,
        ExecutionPlane.ANALYSIS,
        "quartz.idea_foundry.analysis.PhysicsFalsifierSkeleton",
        None,
        ("null temperature model", "bootstrap redundancy", "no-scale-collapse null"),
        ("beta residual KL", "fragment agreement", "susceptibility", "curve collapse"),
        ("dashboard artifact schema", "explicit null models", "transition kernels for theorem tests"),
    ),
    AxisSpec(
        "A18_diffusion_regularized_evaluator",
        "Deterministic evaluator with training-only denoising",
        AxisState.SEED,
        ExecutionPlane.TRAINING,
        "quartz.idea_foundry.representation.DiffusionRegularizedEvaluatorSpec",
        None,
        ("current ResNet", "plain U-Net", "masked denoising", "latent denoising"),
        ("same-time Elo", "policy KL", "value calibration", "items/s"),
        ("parameter/FLOP-matched U-Net", "deterministic inference API", "joint/fine-tune schedule"),
    ),
    AxisSpec(
        "A19_rw_rest_lite_evaluator",
        "RW-ResT-AZ-40/144-Lite evaluator",
        AxisState.SEED,
        ExecutionPlane.TRAINING,
        "quartz.idea_foundry.representation.RwRestLiteSpec",
        None,
        ("current ResNet", "static WS Lite", "local-global hybrid", "full BasicBlock upper bound"),
        ("same-time Elo", "boards/s", "VRAM", "graph-seed variance", "size OOD"),
        ("model implementation", "graph-seed proxy screen", "static-pruning export"),
    ),
    AxisSpec(
        "A20_cpu_incremental_student",
        "CPU incremental pattern-codebook student",
        AxisState.SEED,
        ExecutionPlane.TRAINING,
        "quartz.idea_foundry.representation.CpuIncrementalStudentSpec",
        None,
        ("small CNN", "ONNX CPU", "Rapfi-like pattern net", "PVS same evaluator"),
        ("positions/s", "nodes/s", "same-time Elo", "incremental hit rate", "J/move"),
        ("codebook generator", "incremental accumulator", "quantized kernel", "distillation data"),
    ),
    AxisSpec(
        "A21_regret_state_archive",
        "Regret/instability state archive",
        AxisState.SEED,
        ExecutionPlane.TRAINING,
        "quartz.idea_foundry.representation.RegretStateArchiveSkeleton",
        None,
        ("standard self-play", "uniform archive", "Go-Exploit", "regret-guided restart"),
        ("Elo per NN eval", "value loss", "coverage", "archive ESS"),
        ("record schema", "deduplication", "importance correction", "fixed-compute campaign"),
    ),
    AxisSpec(
        "A22_ments_decaying_entropy",
        "MENTS / decaying Boltzmann comparator",
        AxisState.CONDITIONAL,
        ExecutionPlane.RUST_ONLINE,
        "quartz.idea_foundry.decision.MentsDecayingEntropySkeleton",
        "foundry_axes::MentsAxis",
        ("PUCT", "MENTS", "BTS", "DENTS"),
        ("simple regret", "sample efficiency", "tactical dilution", "entropy schedule"),
        ("root/shallow-only wiring", "decay schedule", "same-objective final readout"),
    ),
    AxisSpec(
        "A23_graph_state_sharing_consistency",
        "Graph-state sharing and path-consistency observer",
        AxisState.SEED,
        ExecutionPlane.POSTHOC,
        "quartz.idea_foundry.systems.GraphStateSharingConsistencySkeleton",
        "foundry_axes::GraphConsistencyAxis",
        ("TT eval cache", "tree statistics", "MCGS"),
        ("state reuse", "path disagreement", "memory", "strength"),
        ("state-node/parent-edge separation", "occurrence telemetry", "MCGS comparator"),
    ),
    AxisSpec(
        "A24_symmetry_orbit_audit",
        "Symmetry-orbit and representation invariance audit",
        AxisState.MECHANISM_VALID,
        ExecutionPlane.ANALYSIS,
        "quartz.idea_foundry.analysis.SymmetryOrbitAuditSkeleton",
        None,
        ("negative index-dependent controls",),
        ("max equivariance error", "JSD error", "zero-mass clone robustness"),
        ("register every new operator", "game-specific transform maps"),
    ),
)

_BY_ID = {spec.axis_id: spec for spec in AXIS_SPECS}


def get_axis_spec(axis_id: str) -> AxisSpec:
    try:
        return _BY_ID[axis_id]
    except KeyError as exc:
        raise KeyError(f"unknown idea-foundry axis: {axis_id}") from exc


def axis_ids() -> tuple[str, ...]:
    return tuple(spec.axis_id for spec in AXIS_SPECS)
